// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qahnitknldzdfywhhgsy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFhaG5pdGtubGR6ZGZ5d2hoZ3N5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMzY3NDQsImV4cCI6MjA1ODYxMjc0NH0.17hZ-r0QaBQNP7B6uNaKMQtjU5VA8XN7CKPbnZH5Y5g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);