// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tfxbxxyswdzdlrtwyjwy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmeGJ4eHlzd2R6ZGxydHd5and5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMjM4MjgsImV4cCI6MjA2Njg5OTgyOH0.5dr78jatjjmoNdwXfQKtLuAIHhwnf4vTuB0ftq4NWtY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});